### ISSUE TITLE
search-by-category gets removed after update

### ISSUE THREAD

**Issue by poonasor** [simpliko/wpadverts-snippets#3]
I upload the .php file into plugins and once i do that it says theres a update - i update and the plugin php file gets deleted and plugin removed

**Comment by gwin** [comment]
This is because on WP.org there is a plugin named search-by-category which is a different plugin than search-by-category snippet available here, updating basically replaces the snippet with the plugin from WP.org.

You should install the snippet again and do not update it.

If you do not want to see the update notification then either change version to 999 in the search-by-category.php or rename the search-by-category directory to something else.
